import {
  SERVER_URL,
  DEV_MODE,
  TURNSTILE_SITEKEY,
  EMOJI_URL,
  NERIMITY_CDN,
  APP_VERSION,
} from '@env';

export default {
  SERVER_URL: SERVER_URL,
  APP_VERSION: APP_VERSION as string | undefined,
  DEV_MODE: DEV_MODE === 'true',
  TURNSTILE_SITEKEY: TURNSTILE_SITEKEY,
  EMOJI_URL: EMOJI_URL,
  NERIMITY_CDN: NERIMITY_CDN,
};
